# Generated by Django 5.1.2 on 2024-11-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='photo')),
                ('telefono', models.CharField(max_length=15)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('libre', 'Libre'), ('no_disponible', 'No Disponible')], default='libre', max_length=15)),
            ],
        ),
    ]
