# Generated by Django 5.1.2 on 2024-11-11 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios', '0002_alter_espaciopublico_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaciopublico',
            name='telefono',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe\n                       ingresarse en el formato: '999999999'.", regex='^\\d{11}$')]),
        ),
    ]
