# Generated by Django 5.1.2 on 2024-11-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios', '0004_alter_espaciopublico_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaciopublico',
            name='estado',
            field=models.CharField(choices=[('libre', 'Disponible'), ('no_disponible', 'No Disponible')], default='libre', max_length=15),
        ),
    ]
