# Generated by Django 5.1.2 on 2024-11-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios', '0005_alter_espaciopublico_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaciopublico',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible')], default='disponible', max_length=15),
        ),
    ]
