# Generated by Django 5.1.2 on 2024-11-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios', '0007_espaciopublico_espacio_especial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaciopublico',
            name='limpieza',
            field=models.BooleanField(default=False),
        ),
    ]
