# Generated by Django 5.1.2 on 2024-11-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios', '0008_espaciopublico_limpieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaciopublico',
            name='subespacios',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
