# Generated by Django 5.1.2 on 2024-11-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios', '0008_espaciopublico_limpieza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaciopublico',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='espacios_publicos/%Y/%m/%d', verbose_name='photo'),
        ),
    ]
