# Generated by Django 5.1.2 on 2024-11-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios', '0009_alter_espaciopublico_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaciopublico',
            name='fotos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
