# Generated by Django 5.1.2 on 2024-11-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios', '0009_espaciopublico_subespacios'),
        ('gestion_espacios', '0010_alter_espaciopublico_fotos'),
    ]

    operations = [
    ]
