# Generated by Django 5.1.2 on 2024-11-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_alter_customuser_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='numero_telefono',
        ),
        migrations.AddField(
            model_name='customuser',
            name='apellidos',
            field=models.CharField(default='No especificado', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='direccion_postal',
            field=models.CharField(default='No especificada', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(default='No especificado', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('usuario_final', 'Usuario Final'), ('personal_administrativo', 'Personal Administrativo'), ('superusuario', 'Superusuario')], default='usuario_final', max_length=30),
        ),
    ]
