# Generated by Django 5.1.2 on 2024-11-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_remove_customuser_numero_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='direccion_postal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
