# Generated by Django 5.1.2 on 2024-11-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_ayuntamiento', models.TextField(default='El Ayuntamiento de Villanueva de las Cruces es el\n        alma de un municipio lleno de encanto, historia y tradiciones. Con eventos\n        como la “Candela” en honor a San Sebastián y una deliciosa gastronomía que\n        incluye el potaje de gurumelos, este pintoresco pueblo de casas blancas\n        invita  a vecinos y visitantes a disfrutar de su cultura y sentirse como un\n        Cruceño más.')),
            ],
        ),
    ]
