# Generated by Django 5.1.2 on 2024-11-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_configuracionadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AyuntamientoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
