# Generated by Django 5.1.2 on 2024-11-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ayuntamientoinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracion',
        ),
        migrations.DeleteModel(
            name='ConfiguracionAdmin',
        ),
    ]
