# Generated by Django 5.1.2 on 2024-11-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reservas', '0003_alter_reserva_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
