# Generated by Django 5.1.2 on 2024-11-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reservas', '0005_solicitudreservaespecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudreservaespecial',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CANCELADA', 'Cancelada'), ('ACEPTADA', 'Aceptada')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitudreservaespecial',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
