# Generated by Django 5.1.2 on 2024-11-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reservas', '0006_solicitudreservaespecial_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
