# Generated by Django 5.1.2 on 2024-11-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reservas', '0007_reserva_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='solicitudreservaespecial',
            unique_together=set(),
        ),
    ]
