# Generated by Django 5.1.2 on 2024-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios', '0011_merge_20241125_1142'),
        ('gestion_reservas', '0007_reserva_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='solicitudreservaespecial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reserva',
            name='subespacio',
            field=models.CharField(default='No procede', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('espacio', 'subespacio', 'fecha', 'hora_inicio')},
        ),
    ]
