# Generated by Django 5.1.2 on 2024-11-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reservas', '0008_alter_reserva_unique_together_and_more'),
        ('gestion_reservas', '0008_alter_reserva_unique_together_reserva_subespacio_and_more'),
    ]

    operations = [
    ]
